peach/urls.py
# Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
from django.conf.urls.defaults import *
from django.conf import settings
 
urlpatterns = patterns('',
	(r'^$', 'peach.views.index'),

	(r'^m/$', 'peach.mobile_views.index'),
	(r'^m/(?P<namespace>[^/]+)/$', 'peach.mobile_views.namespace'),
	(r'^m/(?P<namespace>[^/]+)/(?P<name>[^/]+)/$', 'peach.mobile_views.wiki'),

	(r'^photo/(?P<id>[\d]+)/$' , 'peach.views.photo_image'),
	(r'^photo/(?P<id>[\d]+)/(?P<size>[^/]+)/$' , 'peach.views.photo_image'),
	(r'^(?P<username>[^/]+)/(?P<namespace>[^/]+)/$', 'peach.views.namespace'),
	(r'^(?P<username>[^/]+)/(?P<namespace>[^/]+)/(?P<name>[^/]+)/$', 'peach.views.wiki'),
	(r'^(?P<username>[^/]+)/(?P<namespace>[^/]+)/(?P<name>[^/]+)/history/(?P<id>[^/]+)$' , 'peach.views.wiki_page_log'),
	(r'^(?P<username>[^/]+)/(?P<namespace>[^/]+)/(?P<name>[^/]+)/history/$' , 'peach.views.wiki_history'),
	(r'^(?P<username>[^/]+)/(?P<namespace>[^/]+)/(?P<name>[^/]+)/file/(?P<id>[\d]+)/$' , 'peach.views.file'),
	(r'^(?P<username>[^/]+)/(?P<namespace>[^/]+)/(?P<name>[^/]+)/print/$' , 'peach.views.wiki_print'),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
from django.core.urlresolvers import reverse

from transmutable import API

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^favicon.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/favicon.gif'}, name='favicon'),
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^admin/', include(admin.site.urls)),

	url(r'^phlogiston/', include('phlogiston.urls', app_name='phlogiston')),

	url(r'^api/notes/', include('peach.api_urls', app_name='peach_api')),

	(r'^api/', include(API.urls)),

	url(r'^accounts/profile/$', 'django.views.generic.simple.redirect_to', {'url': '/p/profile/'}, name='profile'),
	url(r'^accounts/login/$', 'django.views.generic.simple.redirect_to', {'url': '/p/login/'}, name='login'),

	(r'^search/$', 'search_views.search'),

	url(r'^p/', include('person.urls', app_name='person')),
	url(r'^notes/', include('peach.urls', app_name='peach')),
	url(r'^staff/', include('apple.urls', app_name='apple')),
	url(r'^', include('banana.urls', app_name='banana')),
)

if settings.DEBUG:
	urlpatterns += patterns('',
		(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	)

peach/models.py
# Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
import re
import os
import urllib
import logging
import os.path
import traceback
import unicodedata

from django.db import models
from django.conf import settings
from django.http import HttpResponse
from django.utils.html import strip_tags
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from django.template.loader import render_to_string

from templatetags.wikitags import wiki
from person.models import ThumbnailedModel

def clean_url_element(element):
	"""Removes undesireables like forwards slashes from url elements"""
	if not element: return element
	return element.replace('/','-').replace('&', '-').replace('#', '-')

class NamespaceManager(models.Manager):
	def public(self): return self.filter(public=True)
	def public_not_archived(self): return self.filter(public=True).filter(archive=False)
	def public_archived(self): return self.filter(public=True).filter(archive=True)
	def private_not_archived(self): return self.filter(public=False).filter(archive=False)
	def private_archived(self): return self.filter(public=False).filter(archive=True)
	def not_archived(self): return self.filter(archive=False)
	def archived(self): return self.filter(archive=True)

class Namespace(models.Model):
	name = models.CharField(max_length=1000, blank=False, null=False)
	display_name = models.CharField(max_length=1000, blank=False, null=False)
	owner = models.ForeignKey(User, blank=False, null=False, related_name='namespaces')
	public = models.BooleanField(default=True)
	archive = models.BooleanField(default=False)
	
	objects = NamespaceManager()

	def save(self, *args, **kwargs):
		self.name = slugify(self.display_name)
		super(Namespace, self).save(*args, **kwargs)
		
	@property
	def splash_page(self): return WikiPage.objects.get_or_create(namespace=self, name='SplashPage')[0]

	def serialize_fields(self): return ['id', 'name', 'display_name', 'owner_username']

	@property
	def owner_username(self): return self.owner.username

	@staticmethod
	def can_create(user): return user.is_authenticated()
	def can_read(self, user):
		if self.public: return True
		if self.owner == user: return True
		return False
	def can_update(self, user): return self.owner == user
	def can_delete(self, user): return self.owner == user

	def get_api_url(self): 
		return reverse('api_dispatch_detail', args=['v0.1', 'peach/namespace', self.id])

	@models.permalink
	def get_absolute_url(self): return ('peach.views.namespace', [], { 'username':self.owner.username, 'namespace':self.name })
	def __unicode__(self): return self.name

	class Meta:
		unique_together = ('owner', 'name')
		ordering = ('name',)

class WikiPageManager(models.Manager):
	def get_or_create(self, **kwargs):
		namespace = kwargs['namespace']
		return super(WikiPageManager, self).get_or_create(namespace=namespace, name=kwargs['name'])
	
class WikiPage(models.Model):
	"""A named chunk of markdown formatted text."""
	namespace = models.ForeignKey(Namespace, blank=False, null=False, related_name='pages', editable=False)
	name = models.CharField(max_length=255, blank=False, null=False)
	content = models.TextField(blank=False, null=False, default='')
	rendered = models.TextField(blank=True, null=True, editable=False)
	objects = WikiPageManager()

	def serialize_fields(self): return ['id', 'namespace_id', 'name', 'content', 'rendered', 'get_absolute_url']

	@property
	def public_url(self):
		return reverse('peach.views.wiki', args=[], kwargs={ 'username':self.namespace.owner.username, 'namespace':self.namespace.name, 'name':self.name })

	@models.permalink
	def get_absolute_url(self):
		'''
		NOTE: This will return the URL to the Namespace (not the public page URL) for SplashPage WikiPages.
		To get the public page URL, use WikiPage.get_public_url()
		'''
		if self.name == "SplashPage": return ('peach.views.namespace', [], {'username':self.namespace.owner.username, 'namespace':self.namespace.name })
		return ('peach.views.wiki', [], { 'username':self.namespace.owner.username, 'namespace':self.namespace.name, 'name':self.name })

	@models.permalink
	def get_mobile_url(self):
		if self.name == "SplashPage": return ('peach.mobile_views.namespace', [], { 'namespace':self.namespace.name })
		return ('peach.mobile_views.wiki', [], { 'namespace':self.namespace.name, 'name':self.name })

	def get_api_url(self): 
		return reverse('api_dispatch_detail', args=['v0.1', 'peach/wiki-page', self.id])

	def __unicode__(self): return '%s %s' % (self.name, self.id)

	def save(self, *args, **kwargs):
		"""When saving the content, render via markdown and save to self.rendered"""
		self.rendered = wiki(self.content)
		self.name = clean_url_element(self.name)
		super(WikiPage, self).save(*args, **kwargs)
		WikiPageLog.objects.create(wiki_page=self, content=self.content)

	class Meta:
		ordering = ('name',)
		unique_together = ('namespace', 'name')


class WikiPageLog(models.Model):
	"""A historical version of a WikiPage."""
	wiki_page = models.ForeignKey(WikiPage, blank=False, null=False)
	content = models.TextField(blank=False, null=False)
	created = models.DateTimeField(auto_now_add=True)
	@models.permalink
	def get_absolute_url(self):
		return ('peach.views.wiki_page_log', [], { 'username':self.wiki_page.namespace.owner.username, 'namespace':self.wiki_page.namespace.name, 'name':self.wiki_page.name, 'id':self.id })
	def __unicode__(self):
		return '%s: %s' % (self.wiki_page.name, self.created)
	class Meta:
		ordering = ('-created',)

class WikiConstant(models.Model):
	"""A piece of wikitext which can be included (but not wiki rendered) in multiple wiki pages
	The syntax is \%constant_name\%
	"""
	name = models.CharField(max_length=512, null=False, blank=False)
	constant = models.TextField(blank=False, null=False)
	def __unicode__(self):
		return self.name

class WikiFile(models.Model):
	"""A non-image file associated with a WikiPage."""
	file = models.FileField(upload_to='wiki_file', blank=False, null=False)
	wiki_page = models.ForeignKey(WikiPage, blank=False, null=False)
	title = models.CharField(max_length=1024, null=True, blank=True)
	description = models.TextField(blank=True, null=True)
	created = models.DateTimeField(auto_now_add=True)
	def display_name(self):
		if self.title: return self.title
		return os.path.basename(self.file.name)
	@models.permalink
	def get_absolute_url(self):
		return ('peach.views.file', (), { 'username':self.owner.username, 'namespace':self.wiki_page.namespace.name, 'name':self.wiki_page.name, 'id':self.id })
	class Meta:
		ordering = ['-created']
	def __unicode__(self):
		return str(self.file)

class WikiPhoto(ThumbnailedModel):
	"""An image and metadata associated with a WikiPage."""
	image = models.ImageField(upload_to='wiki_photo', blank=False)
	wiki_page = models.ForeignKey(WikiPage, related_name='wiki_photos', blank=False, null=False)
	title = models.CharField(max_length=1024, null=True, blank=True)
	caption = models.CharField(max_length=1024, null=True, blank=True)
	description = models.TextField(blank=True, null=True)
	created = models.DateTimeField(auto_now_add=True)

	@property
	def display_name(self):
		if self.title: return self.title
		return os.path.basename(self.image.name)

	@property
	def web_thumb_url(self):
		return reverse('peach.views.photo_image', args=[], kwargs={'id': self.id, 'size':'thumb'})

	@property
	def web_image_url(self):
		return reverse('peach.views.photo_image', args=[], kwargs={'id': self.id, 'size':'web'})

	@property
	def full_image_url(self):
		return reverse('peach.views.photo_image', args=[], kwargs={'id': self.id, 'size':'full'})

	class Meta:
		ordering = ['created']

	def __unicode__(self): return str(self.image)

peach/views.py
# Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
import datetime
import calendar
import traceback

from django.db.models import Q
from django.contrib import auth
from django.conf import settings
from django.core.cache import cache
from django.core.mail import send_mail
from django.utils import feedgenerator
from django.utils.html import strip_tags
from django.template import RequestContext
from django.template import Context, loader
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.contrib.comments.models import Comment
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
import django.contrib.contenttypes.models as content_type_models
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse, Http404, HttpResponseServerError, HttpResponseRedirect, HttpResponsePermanentRedirect

from transmutable import serialize_query_set

from models import *
from forms import *
from api import WikiPhotoResource

@login_required
def index(request):
	return render_to_response('peach/index.html', { }, context_instance=RequestContext(request))

def namespace(request, username, namespace):
	ns = get_object_or_404(Namespace, owner__username=username, name=namespace)
	if not ns.can_read(request.user): return render_to_response('peach/not_authed.html', {}, context_instance=RequestContext(request))
	page = WikiPage.objects.get_or_create(namespace=ns, name='SplashPage')[0]
	if request.user == ns.owner and not request.GET.get('public') == 'true':
		return render_to_response('peach/namespace.html', { 'namespace':ns, 'wiki_pages':WikiPage.objects.filter(namespace=ns).exclude(name='SplashPage'), 'page':page }, context_instance=RequestContext(request))
	else:
		return render_to_response('peach/namespace_public.html', { 'namespace':ns, 'wiki_pages':WikiPage.objects.filter(namespace=ns).exclude(name='SplashPage'), 'page':page }, context_instance=RequestContext(request))

def photo_image(request, id, size=None):
	'''Returns the photo image data iff the request user is allowed to read the namespace'''
	if size == None: size = 'web'
	if not size in ['thumb', 'web', 'full']:
		raise Http404('Invalid size')
	photo = get_object_or_404(WikiPhoto, pk=id)
	if not photo.wiki_page.namespace.can_read(request.user):
		return HttpResponse(status=403)
	if size == 'full':
		full_path = photo.image.full_path
		url = photo.image.url
	elif size == 'thumb':
		filename, miniature_filename, miniature_dir, url = photo.get_or_create_thumbnail(width=photo.WEB_THUMB_WIDTH, height=photo.WEB_THUMB_HEIGHT)
		full_path = os.path.join(miniature_dir, miniature_filename)
	elif size == 'web':
		filename, miniature_filename, miniature_dir, url = photo.get_or_create_thumbnail(width=photo.WEB_WIDTH, height=photo.WEB_HEIGHT)
		full_path = os.path.join(miniature_dir, miniature_filename)
	return photo.http_response_for_image_field(full_path, url, photo.title)

def file(request, namespace, name, id):
	file = get_object_or_404(WikiFile, wiki_page__name=name, pk=id)
	if not file.wiki_page.namespace.can_read(request.user): return render_to_response('peach/not_authed.html', {}, context_instance=RequestContext(request))
	return render_to_response('peach/file.html', { 'file':file }, context_instance=RequestContext(request))

def wiki(request, username, namespace, name):
	ns = get_object_or_404(Namespace, name=namespace, owner__username=username)
	page = get_object_or_404(WikiPage, namespace=ns, name=name)
	if not page.namespace.can_read(request.user): return render_to_response('peach/not_authed.html', {}, context_instance=RequestContext(request))

	if request.method == 'POST':
		if not page.namespace.can_update(request.user):
			return HttpResponse('Not authed', status=403)
		wiki_photos_form = WikiPhotosForm(request.POST, request.FILES)
		if wiki_photos_form.is_valid():
			photos = wiki_photos_form.save(page, request.FILES)
			serialized_photos = serialize_query_set(photos, WikiPhotoResource, request)
			return HttpResponse(serialized_photos, status=200)
		else:
			print 'not valid', wiki_files_form
			return HttpResponse('Form not valid', status=400)

	return render_to_response('peach/wiki.html', { 'page':page }, context_instance=RequestContext(request))

def wiki_print(request, username, namespace, name):
	namespace = get_object_or_404(Namespace, name=namespace, owner__username=username)
	page = get_object_or_404(WikiPage, namespace=namespace, name=name)
	if not page.namespace.can_read(request.user): return render_to_response('peach/not_authed.html', {}, context_instance=RequestContext(request))
	return render_to_response('peach/wiki_print.html', { 'page':page }, context_instance=RequestContext(request))

@login_required
def wiki_history(request, username, namespace, name):
	ns = get_object_or_404(Namespace, name=namespace, owner__username=username)
	if not ns.can_read(request.user): return render_to_response('peach/not_authed.html', {}, context_instance=RequestContext(request))
	page = get_object_or_404(WikiPage, namespace=ns, name=name)
	return render_to_response('peach/wiki_history.html', { 'page':page }, context_instance=RequestContext(request))

@login_required
def wiki_page_log(request, username, namespace, name, id):
	page_log = get_object_or_404(WikiPageLog, wiki_page__name=name, pk=id)
	ns = get_object_or_404(Namespace, name=namespace, owner__username=username)
	if request.method == 'POST' and request.POST.get('revert', None):
		if not ns.can_update(request.user): return HttpResponseRedirect(page_log.get_absolute_url())
		page_log.wiki_page.content = page_log.content
		page_log.wiki_page.save()
		return HttpResponseRedirect(page_log.wiki_page.get_absolute_url())
	if not ns.can_read(request.user): return render_to_response('peach/not_authed.html', {}, context_instance=RequestContext(request))
	return render_to_response('peach/wiki_page_log.html', { 'page_log':page_log  }, context_instance=RequestContext(request))

peach/templates/peach/base.html
{% extends "base/base.html" %}

{% block extra-links %}
	<link rel="stylesheet" href="{{STATIC_URL}}banana/banana.css" />
	<link rel="stylesheet" href="{{STATIC_URL}}peach/peach.css" />
{% endblock %}
{% block app-head %}
	<script src="{{STATIC_URL}}peach/peach.js"></script>
{% endblock %}

peach/templates/peach/file.html
{% extends "peach/base.html" %}

{% block sub-title %}{{ file.display_name }} | {% endblock %}

{% load imagetags %}
{% block content %}
<h1>Wiki File on <a href="{{ file.wiki_page.get_absolute_url }}">{{ file.wiki_page.name }}</a>: {{ file.display_name }}</h1>

<table>
	{% if file.description %}
	<tr>
		<th>description:</th>
		<td>{{ file.description }}</td>
	</tr>
	{% endif %}
	{% if file.created %}
	<tr>
		<th>created:</th>
		<td>{{ file.created }}</td>
	</tr>
	{% endif %}
	<tr>
		<th>original file:</th>
		<td><a href="{{ file.file.url }}">{{ file.file.url }}</a></td>
	</tr>
</table>

{% endblock %}

peach/templates/peach/index.html
{% extends "peach/base.html" %}
{% load imagetags %}
{% block sub-title %}Notes | {% endblock %}

{% block sub-style %}
.welcome-title { text-align: center; }
#namespace-form { display: inline; }
#namespace-form input[type=text] { width: 20em; }
.namespace-list li { margin-left: 20px; list-style-type: disc; margin-bottom: 8px; }
.namespace-list .alert {
	padding-right: 8px;
	min-height: 8em;
}
{% if not request.user.namespaces.all %}
	.create-namespace-view {
		text-align: center;
	}
{% endif %}
{% endblock %}

{% block sub-head %}
<script>
window.newNotesTourView = null;
window.newUser = {% if request.user.namespaces.all %}false{% else %}true{% endif %};
window.createNamespaceForm = null;

window.schema.on('populated', _.once(initPage));

function initPage(){
	$('#notes-nav').addClass('active');

	window.createNamespaceForm = new peach.views.CreateNamespaceForm({
		'saveCallback':handleNamespaceCreated
	});
	$('#content').prepend(window.createNamespaceForm.el);

	if(newUser){
		window.newNotesTourView = new peach.views.NewNotesTourView();
		$('#content').prepend(window.newNotesTourView.el);
	}
}

function handleNamespaceCreated(namespace){
	var namespaceUrl = window.urlLoader.urls.peach.username_namespace('{{request.user.username}}', namespace.get('name'));
	if(newUser){
		namespaceUrl += '?new=true';
	}
	document.location.href = namespaceUrl;
}
</script>
{% endblock %}

{% block content %}
	{% if request.user.namespaces.all %}
		<div class="row-fluid">
			<ul id="public-list" class="namespace-list span4">
				<h3 class="section-title">Public</h3>
				{% if not request.user.namespaces.public_not_archived %}
					<div class='alert alert-info'>
						Notes which are visible to anyone.
					</div>
				{% endif %}
				{% for namespace in request.user.namespaces.public_not_archived %}
					<li>
						<a href="{{ namespace.get_absolute_url }}">{{ namespace.display_name }}</a>
					</li>
				{% endfor %}
				{% for namespace in request.user.namespaces.public_archived %}
					<li class="archived-namespace-item">
						<a href="{{ namespace.get_absolute_url }}">{{ namespace.display_name }}</a>
					</li>
				{% endfor %}
			</ul>
			<ul id="private-list" class="namespace-list span4">
				<h3 class="section-title">Private</h3>
				{% if not request.user.namespaces.private_not_archived %}
					<div class='alert alert-info'>
						Notes which are visible only to you.
					</div>
				{% endif %}
				{% for namespace in request.user.namespaces.private_not_archived %}
					<li>
						<a href="{{ namespace.get_absolute_url }}">{{ namespace.display_name }}</a>
					</li>
				{% endfor %}
				{% for namespace in request.user.namespaces.private_archived %}
					<li class="archived-namespace-item">
						<a href="{{ namespace.get_absolute_url }}">{{ namespace.display_name }}</a>
					</li>
				{% endfor %}
			</ul>
		</div>
	{% endif %}
{% endblock %}

peach/templates/peach/not_authed.html
{% extends "peach/base.html" %}
{% load imagetags %}
{% block sub-title %}Not authorized | {% endblock %}

{% block sub-style %}
{% endblock %}

{% block content %}
<h1>Not authorized:</h1>

<p>Sorry, but this document has been marked private by its owner.</p>
{% endblock %}

peach/templates/peach/photo.html
{% extends "peach/base.html" %}

{% block sub-title %}{{ photo.display_name }} | {% endblock %}

{% load imagetags %}
{% block content %}
<h1>Wiki Photo on <a href="{{ photo.wiki_page.get_absolute_url }}">{{ photo.wiki_page.name }}</a>: {{ photo.display_name }}</h1>

<img style="margin-bottom: 20px; " src="{{ photo.image.url|fit_image:"600x600" }}" />

<table>
	{% if photo.caption %}
	<tr>
		<th>caption:</th>
		<td>{{ photo.caption }}</td>
	</tr>
	{% endif %}
	{% if photo.description %}
	<tr>
		<th>description:</th>
		<td>{{ photo.description }}</td>
	</tr>
	{% endif %}
	{% if photo.created %}
	<tr>
		<th>created:</th>
		<td>{{ photo.created }}</td>
	</tr>
	{% endif %}
	<tr>
		<th>original file:</th>
		<td><a href="{{ photo.image.url }}">{{ photo.image.url }}</a></td>
	</tr>
</table>

{% endblock %}

peach/templates/peach/wiki_edit.html
{% extends "peach/base.html" %}
{% load imagetags %}

{% block sub-title %}Edit | {{ page.name }} | {% endblock %}

{% block sub-style %}
#id_content { width: 99%; height: 500px; }
#page-form { width: 100%; margin-bottom: 10px;}
#wiki-page-editor button { margin-left: 10px; float: right; }
.wiki-photo-item { margin-top: 10px; }
#cheat-sheet, #cheat-sheet h3, #cheat-sheet h4 { color: #666; }
#cheat-sheet h4 { margin-top: 1.5em; }
{% endblock %}

{% block sub-head %}
<script src="{{STATIC_URL}}peach/wiki_page_views.js"></script>
<script>
$(document).ready(function(){
    window.wikiPageEditView = new transmutable.WikiPageEditView({
		wikiPageId: {{ page.id }},
		namespace: '{{ page.namespace.name }}',
		name: '{{ page.name }}',
		username: '{{ request.user.username }}',
		el: $("#wiki-page-editor")
	});
});


function saveThenAddFile(){
	$("#page-form").attr('action', '.?next={% url peach.views.wiki_add page.namespace.owner.username page.namespace.name page.name %}');
	$("#page-form").submit();
}
</script>
{% endblock %}

{% block content %}
	<ul class="breadcrumb">
		<li>
			<a href="{% url peach.views.index %}">Notes</a>
		</li>
		<li><a href="{{ page.namespace.get_absolute_url }}">{{ page.namespace.display_name }}</a></li>
		<li><a href="{{ page.get_absolute_url }}">{{ page.name }}</a></li>
		<li class="active">edit</li>
	</ul>

<div class="row">
	<div id="wiki-page-editor" class="col-sm-12 col-md-10">
		
	</div>

	<div id="cheat-sheet" class="col-sm-12 col-md-2">
		<h3>Cheat Sheet:</h3>
		<p>Format your text like so:</p>

		<h4>Use # for headings</h4>
		# Biggest<br/>
		## Second Biggest<br/>
		### Third Biggest<br/>
		
		<h4>Use - for lists</h4>
		- Apples<br/>
		- Oranges<br/>
		- Aesthetics<br/>

		<h4>Create links</h4>
		[Example](http://exa.com)

		<p style="margin-top: 2em;">See the <a target="_new" href="http://daringfireball.net/projects/markdown/syntax">Markdown</a> page for more formatting options.</p>
	</div>
</div>

<div class="row">
	<div class="wiki-control-links">
		<!-- [<a onclick="saveThenAddFile(); return false;" href="{% url peach.views.wiki_add page.namespace.owner.username page.namespace.name page.name %}">add file or photo</a>]</div> -->

	{% if page.wikiphoto_set.all %}
	<h3>Photos:</h3>
	<p>To include a photo in the page, type a photo tag which starts with "Photo" and ends with the photo id, like so "Photo5".<br/>  You will find the photo tag above each photo listed below.</p>
	{% endif %}
	{% for photo in page.wikiphoto_set.all %}
		<div class="wiki-photo-item">
			Photo{{ photo.id }}<br/>
			<a href="{{ photo.get_absolute_url }}">
				<img alt="{{ photo.display_name }}" title="{{ photo.display_name }}" src="{{ photo.image.url|fit_image:"150x150" }}" /> 
			</a>
		</div>
	{% endfor %}

	{% if page.wikifile_set.all %}
	<h3>Files:</h3>
	{% endif %}
	{% for file in page.wikifile_set.all %}
		<div class="wiki-file-item">
			<a href="{{ file.file.url }}">{{ file.display_name }}</a> <span class="wiki-control-link">[<a href="{{ file.get_absolute_url }}">info</a>]</span>
		</div>
	{% endfor %}
</div>
{% endblock %}

peach/templates/peach/wiki_history.html
{% extends "peach/base.html" %}

{% block sub-title %}History | {{ page.name }} | {% endblock %}

{% block style %}
.wiki-page-log-item { margin: 10px 10px;}
{% endblock %}

{% block content %}
	<ul class="breadcrumb">
		<li>
			<a href="{% url peach.views.index %}">Notes</a>
		</li>
		<li><a href="{{page.namespace.get_absolute_url}}">{{ page.namespace.display_name }}</a></li>
		<li><a href="{{page.get_absolute_url}}">{{ page.name }}</a></li>
		<li class="active">history</li>
	</ul>

{% for log in page.wikipagelog_set.all %}
{% ifchanged log.created.day %}
	<h3>{{ log.created|date:"F j"}}:</h3>
{% endifchanged %}
<div class="wiki-page-log-item">
	<a href="{{ log.get_absolute_url }}">{{ log.created|date:"g:i A" }}</a>
</div>
{% endfor %}
{% endblock %}