person/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('',
	(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'person/login.html'}),
	(r'^logout/$', 'django.contrib.auth.views.logout_then_login', {'login_url': '/' }),

	(r'^register/$', 'person.views.register'),
	(r'^invite/$', 'person.views.invites'),
	(r'^invite/(?P<secret>[^/]+)/$', 'person.views.invite'),
	(r'^profile/$', 'person.views.profile_redirect'),
	(r'^find/$', 'person.views.find_people'),
	(r'^password-reset/$', 'person.views.password_reset'),
	(r'^email-validate/(?P<username>[^/]+)/(?P<secret>[^/]+)/$', 'person.views.email_validate'),
	(r'^edit/photo/$', 'person.views.photo_edit'),
	(r'^edit/password/$', 'person.views.password_edit'),
	(r'(?P<username>[^/]+)/$' , 'person.views.profile'),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
from django.core.urlresolvers import reverse

from transmutable import API

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^favicon.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/favicon.gif'}, name='favicon'),
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^admin/', include(admin.site.urls)),

	url(r'^phlogiston/', include('phlogiston.urls', app_name='phlogiston')),

	url(r'^api/notes/', include('peach.api_urls', app_name='peach_api')),

	(r'^api/', include(API.urls)),

	url(r'^accounts/profile/$', 'django.views.generic.simple.redirect_to', {'url': '/p/profile/'}, name='profile'),
	url(r'^accounts/login/$', 'django.views.generic.simple.redirect_to', {'url': '/p/login/'}, name='login'),

	(r'^search/$', 'search_views.search'),

	url(r'^p/', include('person.urls', app_name='person')),
	url(r'^notes/', include('peach.urls', app_name='peach')),
	url(r'^staff/', include('apple.urls', app_name='apple')),
	url(r'^', include('banana.urls', app_name='banana')),
)

if settings.DEBUG:
	urlpatterns += patterns('',
		(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	)

person/models.py
import os
import Image
import urllib
import os.path
import mimetypes
import datetime, calendar
import unicodedata
import traceback
import logging
import random
import time
import re

from django.db import models
from django.db.models import Q
from django.conf import settings
from django.http import HttpResponse
from django.db.models import signals
from django.dispatch import dispatcher
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.contrib.sites.models import Site
from django.utils.encoding import force_unicode
from django.template.loader import render_to_string

import person.templatetags.imagetags as imagetags

PASSWORD_RESET_SECRET_PARAMETER = "secret"
PASSWORD_RESET_ID_PARAMETER = "id"

class ThumbnailedModel(models.Model):
	"""An abstract base class for models with an ImageField named "image" """

	WEB_WIDTH = 1000
	WEB_HEIGHT = 1000
	WEB_THUMB_WIDTH = 200
	WEB_THUMB_HEIGHT = 200

	def http_response_for_image_field(self, full_path, url, name=None):
		'''
		Returns an HttpResponse which is either a Nginx redirect or an HttpResponse for direct image service
		'''
		mime_type = mimetypes.guess_type(full_path)[0]
		if mime_type is None and name is not None:
			mime_type = mimetypes.guess_type(name)[0]
		if settings.FRONTED_BY_NGINX:
			# This sends a signal header to Nginx so that it takes over service of the file
			response = HttpResponse(mimetype=mime_type)
			response['X-Accel-Redirect'] = url
			return response
		return HttpResponse(file(full_path), content_type=mime_type)

	def get_or_create_thumbnail(self, width=250, height=250):
		if hasattr(self, 'image') and self.image:
			image = self.image
		elif hasattr(self, 'photo') and self.photo:
			image = self.photo.image
		else:
			return ""
		try:
			original_file = settings.MEDIA_URL + image.path[len(settings.MEDIA_ROOT):]
			return imagetags.fit_image_detail(original_file, width, height)
		except:
			traceback.print_exc()
			return None

	@property
	def web_image_url(self):
		return self.get_or_create_thumbnail(ThumbnailedModel.WEB_WIDTH, ThumbnailedModel.WEB_HEIGHT)

	@property
	def web_thumb_url(self):
		return self.get_or_create_thumbnail(ThumbnailedModel.WEB_THUMB_WIDTH, ThumbnailedModel.WEB_THUMB_HEIGHT)

	def thumb(self):
		result_url = self.get_or_create_thumbnail(200, 100)
		if not result_url: return ''
		return """<img src="%s" />""" % result_url
	thumb.allow_tags = True

	class Meta:
		abstract = True

class Photo(ThumbnailedModel):
	image = models.ImageField(upload_to='person_photo', blank=False)
	created = models.DateTimeField(auto_now_add=True)
	class Meta:
		ordering = ['-created']
	def __unicode__(self):
		return str(self.image)

def create_secret(): return User.objects.make_random_password(length=20)

class InviteManager(models.Manager):
	def add_invites(self, number_of_invites, user):
		for i in range(number_of_invites):
			profile = user.get_profile()
			profile.invites.add(Invite.objects.create())
			profile.save()
			
	def distribute_invites(self, num_per_user):
		for profile in UserProfile.objects.filter(user__is_active=True).filter(mute=False):
			num_to_distribute = num_per_user - Invite.objects.filter(inviter=profile, sent_to=None).count()
			if num_to_distribute < 1: continue
			for i in range(0, num_per_user):
				profile.invites.add(Invite.objects.create())
			print 'Gave %s %s invites' % (profile.user.get_full_name(), num_to_distribute)

class Invite(models.Model):
	secret = models.CharField(max_length=1024, blank=False, null=False, default=create_secret)
	sent_to = models.EmailField(default=None, blank=True, null=True)
	used_by = models.ForeignKey(User, blank=True, null=True, related_name='origin_invites')
	created = models.DateTimeField(auto_now_add=True)
	objects = InviteManager()
	def __unicode__(self): return 'Invite %s' % self.id
	@models.permalink
	def get_absolute_url(self):
		return ('person.views.invite', (), { 'secret':self.secret })

class InviteRequest(models.Model):
	email = models.EmailField(blank=False, null=False)
	created = models.DateTimeField(auto_now_add=True)
	def __unicode__(self): return 'InviteRequest: %s' % self.email
	
class UserProfileManager(models.Manager):
	def search(self, search_string):
		"""return user profiles which match ALL terms in one or more of full name, username, location, email, or bio"""
		terms = search_string.split()
		if len(terms) == 0: return None;

		name_query = Q(user__first_name__icontains=terms[0]) 
		for term in terms[1:]: name_query = name_query & Q(user__first_name__icontains=term)

		last_name_query = Q(user__last_name__icontains=terms[0]) 
		for term in terms[1:]: name_query = name_query & Q(user__last_name__icontains=term)

		username_query = Q(user__username__icontains=terms[0]) 
		for term in terms[1:]: username_query = username_query & Q(user__username__icontains=term)

		location_query = Q(location__icontains=terms[0]) 
		for term in terms[1:]: location_query = location_query & Q(location__icontains=term)

		bio_query = Q(bio__icontains=terms[0]) 
		for term in terms[1:]: bio_query = bio_query & Q(bio__icontains=term)

		email_query = Q(user__email=terms[0]) 
		for term in terms[1:]: email_query = email_query & Q(user__email=term)

		return UserProfile.objects.filter(name_query | username_query | location_query | bio_query | email_query).order_by('user__last_name')

class UserProfile(ThumbnailedModel):
	"""Extends the django.contrib.auth User model"""
	user = models.ForeignKey(User, unique=True, related_name='profile')
	photo = models.ForeignKey(Photo, blank=True, null=True)
	location = models.CharField(max_length=1024, blank=True, null=True, help_text="Where you work, for example 'Seattle'")
	bio = models.TextField(null=True, blank=True)
	url = models.URLField(verify_exists=False, null=True, blank=True, max_length=300)
	invites = models.ManyToManyField(Invite, blank=True, null=True, related_name='inviter')
	email_validated = models.BooleanField(default=False, blank=False, null=False)
	tos = models.BooleanField(default=False, blank=False, null=False)
	mute = models.BooleanField(default=False, blank=False, null=False, help_text="Hide this account from public listings.")

	objects = UserProfileManager()
	def invitees(self):
		return UserProfile.objects.filter(user__origin_invites__inviter=self.user)
	def used_invites(self):
		return Invite.objects.filter(inviter=self).exclude(used_by=None)
	def available_invites(self):
		return Invite.objects.filter(inviter=self, sent_to=None)
	def send_email_validation(self):
		site = Site.objects.get_current()
		message = render_to_string('person/email/email_validation.txt', { 'site':site, 'user':self.user })
		subject = '%s email validation' % site.name
		send_mail(subject, message, None, [self.user.email], fail_silently=True)
	def validation_secret(self):
		import md5
		return md5.new('%s-%s-%s' % (self.user.username, self.user.email, self.user.id)).hexdigest()
	@models.permalink
	def get_absolute_url(self):
		return ('person.views.profile', (), { 'username':urllib.quote(self.user.username) })
	def __unicode__(self):
		return self.user.username
	class Meta:
		ordering = ['user__username']
	
def get_display_name(user):
	if user.get_full_name(): return user.get_full_name()
	return user.username
def get_user_url(user):
	return reverse('person.views.profile', kwargs={'username':user.username})
User.get_profile = lambda self: UserProfile.objects.get_or_create(user=self)[0]
User.display_name = get_display_name

# Copyright 2012 Trevor F. Smith (http://trevor.smith.name/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

person/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.html import strip_tags
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse

from models import *

class ProfileForm(forms.ModelForm):

	class Meta:
		model = UserProfile
		fields = ('location', 'url', 'bio')

class ProfileSearchForm(forms.Form):
	terms = forms.CharField(required=True)

class PhotoForm(forms.ModelForm):
	class Meta:
		model = Photo

class InviteRequestForm(forms.ModelForm):
	class Meta:
		model = InviteRequest

class UserCreationForm(forms.ModelForm):
	""" A form that creates a user, with no privileges, from the given username and password. """
	first_name = forms.CharField()
	last_name = forms.CharField()
	username = forms.RegexField(label=_("Username"), max_length=30, regex=r'^\w+$', error_message = _("This value must contain only letters, numbers and underscores."))
	email = forms.EmailField(label=_("Email"))
	password = forms.CharField(label=_("Password"), widget=forms.PasswordInput)
	tos = forms.BooleanField(label="I accept the terms of service.")

	class Meta:
		model = User
		fields = ("username","email")

	def clean_username(self):
		username = self.cleaned_data["username"]
		if User.objects.filter(username__iexact=username).count() > 0: raise forms.ValidationError(("A user with that username already exists."))
		return username.lower()

	def clean_email(self):
		email = self.cleaned_data["email"]
		if User.objects.filter(email__iexact=email).count() > 0:
			raise forms.ValidationError(_("A user with that email already exists."))
		return email

	def save(self, commit=True):
		user = super(UserCreationForm, self).save(commit=False)
		user.set_password(self.cleaned_data["password"])
		user.first_name = self.cleaned_data["first_name"]
		user.last_name = self.cleaned_data["last_name"]
		if commit:
			user.save()
			profile = user.get_profile()
			profile.save()
		return user

class PasswordResetForm(forms.Form):
	email = forms.EmailField(widget=forms.TextInput(attrs={'tabindex':'1'}))

class InviteForm(forms.Form):
	email = forms.EmailField(widget=forms.TextInput(attrs={'tabindex':'1'}))
	message = forms.CharField(max_length=2048, widget=forms.Textarea(attrs={'tabindex':'2'}), required=False)

person/templates/person/base.html
{% extends "base/base.html" %}

{% block extra-links %}
	<link rel="stylesheet" href="{{STATIC_URL}}person/person.css" />
{% endblock %}

{% block app-head %}{% endblock %}

person/templates/person/email_validate.html
{% extends "base/base.html" %}

{% block sub-title %}Email Validation | {% endblock %}

{% block sub-style %}
{% endblock%}

{% block content%}
<h1>Email Validation:</h1>

<h2 style="text-align: center; margin: 100px 0px;">{{ message }}</h2>

{% endblock %}

person/templates/person/find_people.html
{% extends "base/base.html" %}

{% block sub-title %}Find People | {% endblock %}

{% block sub-head %}
<meta name="robots" content="noindex, noarchive, nofollow" />

<script type="text/javascript">
function initialize(){
	$("#id_terms").focus();
}
$(document).ready(function() { initialize(); });
</script>
{% endblock %}
	
{% block style %}
#profile-search-form { text-align: center; }
#profile-search-form input[type=text] { width: 300px; }
#search-results { min-height: 100px; width: 500px; margin-top: 20px; position: relative; left: 280px; }
.person-info-small { margin: 10px 0px; }
{% endblock %}

{% block content%}

<form id="profile-search-form" action="." method="post">
	<h1>Find People on {{ site.name }}:</h1>
	{% for field in profile_search_form  %}{{ field }}{% endfor %}
	<br />
	<input type="submit" value="Go!">
	{% csrf_token %}
</form>

<div id="search-results">
	{% ifequal request.method "POST" %}
		{% if not profile_search_results %}
			<div style="text-align: center;">
				No people could be found.  Dang.
				{% if open_invite and request.user.is_authenticated and request.user.get_profile.available_invites %}
					<div style="margin-top: 20px;">But you have <a href="{% url person.views.invites %}">invites</a>!</div>
				{% endif %}
			</div>
		{% endif %}
	{% endifequal %}
	{% if profile_search_results %}
		<ul>{% for profile in profile_search_results|slice:":100" %}
			<li>
				{% with profile.user.get_absolute_url as profile_link %}
					{% include "person/person_info_small.frag" %}
				{% endwith %}
			</li>
		{% endfor %}</ul>
	{% endif %}
</div>
{% endblock %}

person/templates/person/index.html
{% extends "base/base.html" %}

{% block content%}
<h2>Nothing to see here, folks.</h2>
{% endblock %}

person/templates/person/invite.html
{% extends "person/base.html" %}

{% block sub-title %}Invite | {% endblock %}

{% block sub-head %}
<style>
	#registration-from th {
		width: 10%;
	}
</style>

<script>
	{% include "person/registration_script.frag" %}
</script>
{% endblock %}


{% block content%}
	<div class="row-fluid">
		{% if invite.sent_to %}
			{% if invite.used_by %}
				<p>It appears that this invite has been claimed.</p>
				<p>If you claimed it then you can login (or retrieve a lost password) on our <a href="{% url django.contrib.auth.views.login %}">login page</a>.</p>
			{% else  %}
				{% if request.user.is_authenticated %}
					<p>It appears that you're already logged in.  If you'd like to claim this invite you'll need to log out.</p>
				{% else %}
					<div class="span4 offset1">
						<h1>Claim your invite</h1>
						<form id="registration-form" action="." method="post">
							<table>
								{{ registration_form }}
								<tr><td colspan="2"><input type="submit" value="register" /></td>
							</table>
							{% csrf_token %}
						</form>
					</div>
					<div class="span5 offset1">
						<h2>Work in public</h2>
						<p class='alert alert-info'>Share using tools designed for work (not cat pictures).</p>
						<p class='alert alert-info'>Feel the satisfaction of hitting the 'to-done' button.</p>
						<p class='alert alert-info'>Purge your mind of open loops and nagging thoughts.</p>
						<p class='alert alert-info'>Focus on gratitude for perspective and happiness.</p>
					</div>
				{% endif %}
			{% endif %}
		{% else %}
				<p>We have no record that this invite has been sent.</p>
		{% endif %}
	</div>
{% endblock %}

person/templates/person/invites.html
{% extends "base/base.html" %}

{% block sub-title %}Invites | {% endblock %}

{% block sub-head %}
<style>
#invite-form input[type=text], #invite-form textarea { width: 98%; }
#invite-form th {
	vertical-align: top;
}
#person-list {
	list-style: none;
	margin-left: 0;
}
#person-list li {
	margin-bottom: 1em;
}
#person-list li h4 {
	margin-top: 0.1em;
}
</style>

<script>
$(document).ready(function() {
	$('#invites-nav').addClass('active');
});
</script>
{% endblock %}

{% block content%}
<div class="row-fluid">
	<div class="span4 offset1">
		<h3 class="section-title">You have {{ request.user.get_profile.available_invites.count }} invite{{ request.user.get_profile.available_invites|pluralize }}:</h3>

		{% if message %}
			<h2>{{ message }}</h2>
			<p>You can send more invites and see who's accepted them back on the <a href="{% url person.views.invites %}">invites page</a>.</p>
		{% else %}
			{% if request.user.get_profile.available_invites %}

				<form id="invite-form" action="." method="post">
					<table class="invite-form">
						<tr><td></td><td style="text-align: center;">Fill out this form to send an invite.</td></tr>
						{{ invite_form }}
						<tr><td colspan="2" style="text-align: right;"><input tabindex="3" class="btn" type="submit" value="send invite" /></td></tr>
					</table>
					{% csrf_token %}
				</form>
			{% else %}
				<p>Dang!  At the moment you have no invites.</p>
				<p>Don't worry, we're in talks with the invite factory and they're going to ship a big batch our way.</p>
			{% endif %}
		{% endif %}
	</div>
	<div class="span4 offset1">
		{% if request.user.get_profile.invitees %}
			<h3 class="section-title">People who accepted your invites:</h3>
				<ul id="person-list">
					{% for profile in request.user.get_profile.invitees %}
						{% with profile.user.get_absolute_url as profile_link %}
							{% include "person/person_list_item.frag" %}
						{% endwith %}
					{% endfor %}
				</ul>
		{% endif %}
	</div>
</div>
{% endblock %}

person/templates/person/login.html
{% extends "base/base.html" %}

{% block sub-head %}
<style type="text/css">
	#login-form { max-width: 20em;}
	#login-form th { padding-right: 5px; }
	#login-form label {
		margin-bottom: 0;
		display: block;
		font-weight: normal;
	}
	#login-form input[type=text], #login-form input[type=password] {
		display: block;
		width: 100%;
		margin-bottom: 1em;
	}
	.align-right {
		text-align: right;
	}
</style>
<script>
$(document).ready(function(){
	$('#id_username').focus();
});
</script>
{% endblock %}
	
{% block content%}
<div class="row">
	<div class="col-sm-12 col-md-offset-3 col-md-6">
		{% if form.errors %}
			<p>Your username and password didn't match.</p>
		{% endif %}

		<form id="login-form" method="post" action=".">

			{{ form.username.label_tag }}
			{{ form.username }}

			{{ form.password.label_tag }}
			{{ form.password }}

			<div class="align-right">
				<button class="btn" type="submit">login</button>
				<input type="hidden" name="next" value="{{ next }}" />
				{% csrf_token %}
			</div>
		</form>

		<p style="margin-top: 20px;">
			Don't remember your password?
			Try our <a href="{% url person.views.password_reset %}">password reset page</a>.
		</p>

		{% if open_registration %}
			<p style="margin-top: 20px;">
				Don't have an account yet?  
				Try our <a href="{% url person.views.register %}">registration page</a>.
			</p>
		{% endif %}
	</div>
</div>

{% endblock %}

person/templates/person/login_popup.html
{% extends "base/base.html" %}

{% block title %}Login{% endblock %}

{% block style %}
body { width: 400px; }
form { width: 400px;  }
form table th { vertical-align: top; }
input[type=text], input[type=password] { border: solid 1px #888; width: 200px; margin: 5px 8px 5px 2px; }
input[type=submit] { float: right; }
{% endblock %}

{% block header %}{% endblock %}
{% block content%}

<h2>Login:</h2>

{% if form.errors %}
<p>Your username and password didn't match.</p>
{% endif %}

<form id="login-form" method="post" action="{% url django.contrib.auth.views.login %}">
<table>
<tr><th>{{ form.username.label_tag }}:</th><td>{{ form.username }}</td></tr>
<tr><th>{{ form.password.label_tag }}:</th><td>{{ form.password }}</td></tr>
<tr><td colspan="2" style="text-align: right;">
	<button type="submit">login</button>
	<input type="hidden" name="next" value="{{ next }}" />
</td></tr>
</table>
{% csrf_token %}
</form>

{% endblock %}
{% block footer %}{% endblock %}

person/templates/person/password_reset.html
{% extends "base/base.html" %}

{% block sub-title %}Password Reset | {% endblock %}

{% block sub-style %}
#pw-instructions {
	padding-left: 10px;
	width: 325px;
	margin-bottom: 20px;
}
#password-reset-form {
	text-align: right;
	width: 325px;
}
#password-reset-form input[type=submit]{
	margin-top: 15px;
}
#id_email, #id-password {
	width: 250px;
}
.errorlist {
	color: #D00;
}
#pw-error-message {
	color: #D00;
	font-size: 1.2em;
	font-weight: bold;
	margin: 10px 10px;
}
{% endblock%}

{% block content%}
<h1>Password Reset:</h1>
{% if error_message %}<h2 id="pw-error-message">{{ error_message }}</h2>{% endif %}
	{% if request.user.is_authenticated %}
		<p>You are already logged in.  If you'd like to log out, try the <a href='{% url django.contrib.auth.views.logout_then_login %}'>logout link</a>.</p>
	{% else %}
		{% if request.GET.secret %}
			{% if new_password %}
				<p id="new-password-instructions">Your new password: {{ new_password }}</p>
				<p>Use this password to log in from the <a href='{% url django.contrib.auth.views.login %}'>login page</a>.</p>
			{% else %}
				<!-- hopefully there is an error message above -->
			{% endif %}
		{% else %}
			{% if wait_for_it and not error_message %}
				<p id="pw-instructions">We just sent an email with a link which will allow you to reset your password.</p> 
				<p><strong>If you don't receive the email in 15 minutes, please check your spam folder.</strong></p>
			{% else %}
				<p id="pw-instructions">Enter the email address associated with your account and click "reset your password".</p>
				<p>We will email a link which will allow you to reset your password.</p>
				<p><strong>If you don't receive the email in 15 minutes, please check your spam folder.</strong></p>
				<form id="password-reset-form" action="" method="post">
					{{ password_reset_form.as_p }}
					<input type="submit" tabindex="2" value="reset your password" />
					{% csrf_token %}
				</form>
			{% endif %}
		{% endif %}
	{% endif %}
{% endblock %}

person/templates/person/profile.html
{% extends "person/base.html" %}

{% block sub-title %}Profile for {{ profile.user.get_full_name }} | {% endblock %}

{% block sub-head %}
<script>
$(document).ready(function(){
	if(document.location.hash){
		$('a[href=' + document.location.hash.split('?')[0] + ']').tab('show')
	} else {
		$('a[href=#edit-view]').tab('show')
	}
	if($.urlVar("message")){
		$('#content').prepend('<h2 id="message">' + $.urlVar("message") + '</h2>');
	}
	$('ul.nav-tabs').click(function(){
		hideMessage();
	});
});

function hideMessage(){
	$("#message").hide(1000);
}
</script>
{% endblock %}

{% block sub-style %}
{% endblock %}

{% block content%}

<div class="row-fluid">
	{% ifequal request.user.username profile.user.username %}
		<ul class="nav nav-tabs">
			<li><a href="#edit-view" data-toggle="tab">Edit Profile</a></li>
			<li><a href="#edit-photo" data-toggle="tab">Edit Photo</a></li>
			<li><a href="#change-password" data-toggle="tab">Change Password</a></li>
		</ul>
		<div id="profile-tabs" class="tab-content">
			<div id="edit-view" class="tab-pane">
			{% include "person/profile_form.frag" %}
			</div>
			<div id="edit-photo" class="tab-pane">
			{% include "person/photo_form.frag" %}
			</div>
			<div id="change-password" class="tab-pane">
			{% include "person/password_change.frag" %}
			</div>
		</div>
	{% else %}
		{% include "person/person_info_large.frag" %}
	{% endifequal %}
</div>
{% endblock %}

person/templates/person/register.html
{% extends "person/base.html" %}

{% block sub-title %}Sign Up | {% endblock %}

{% block sub-style %}
#content h1 { text-align: right; }
#registration-form input[type=text], #registration-form input[type=password]{
}
{% endblock %}

{% block sub-head %}
<script>
	{% include "person/registration_script.frag" %}
</script>
{% endblock %}

{% block content%}
	{% if open_registration and not request.user.is_authenticated %}
		<div class="row">
			<div class="col-sm-12 col-md-6">
				<form id="registration-form" action="{% url person.views.register %}" method="post">
					<table>
						{{ registration_form }}
						<tr><td colspan="2" style="text-align: right;"><input id="registration-form-submit" type="submit" value="sign up" /></td>
					</table>
					{% csrf_token %}
				</form>
			</div>
		</div>
	{% elif open_registration and request.user.is_authenticated %}
		<p>It appears that you're already logged in.  If you'd like to register a new account, you'll need to log out.</p>
	{% else %}
		<h2 style="margin: 100px; text-align: center;">We're sorry, but registration is currently closed.</h2>
	{% endif %}

{% endblock %}